spring:
  profiles:
    active: development
---
spring:
  profiles: development
  jpa:
    show_sql: true
    database: H2

    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:assignment
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
debug: true
---
